### ISSUE TITLE
Immersive mode not working after WebVR session is restored 

### ISSUE THREAD

**Issue by keianhzo** [MozillaReality/FirefoxReality#1777]
## Configuration

Firefox Reality version: 1.4
Firefox Reality build ID: b0f21957

Hardware: All

## Steps to Reproduce

1. Open any WebVR demo from the content feed
2. Enter immersive mode
3. Click on the home button
4. Quit FxR and reopen it again
5. The session should be restored with the WebVR demo
6. Try entering immersive mode

## Current Behavior

It doesn't enter immersive mode.

## Expected Behavior

Immersive mode should start.

## Context

![org mozilla vrbrowser dev-20190905-151645](https://user-images.githubusercontent.com/837184/64345272-55cb5380-cff0-11e9-916d-68bf2ee752d1.jpg)

A video can been seen in the following link: https://drive.google.com/open?id=1Qy2ah411PkODorE8LYpHTksCGsW6UUXS

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by MortimerGoro** [comment]
The EnterVR button is not visible in the web, so that means GV didn't return VR displays or it resturned vrDisplay.capabilities.canPresent false. A reload fixes the issue.

I think it's the same issue as #966

**Comment by bluemarvin** [comment]
Looks like it may be a GeckoView bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1583249

**Comment by daoshengmu** [comment]
Firefox Desktop also has this kind of issue, I just fixed it at https://bugzilla.mozilla.org/show_bug.cgi?id=1581988. It maybe not be relative.

**Comment by daoshengmu** [comment]
I am going to jump into the GV bug.

**Comment by philip-lamb** [comment]
@keianhzo Can you please re-test with current master build, to check whether or not it is fixed by Daosheng's patch.

**Comment by keianhzo** [comment]
@philip-lamb still happening with da676ed29a35570008eab3a369053e2833efeab5

**Comment by MortimerGoro** [comment]
I pushed a bugzilla patch to fix this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1587366

**Comment by MortimerGoro** [comment]
Fixed by #1658

**Comment by bluemarvin** [comment]
This is still easily reproducible with GeckoView 71.0.20191014095234

**Comment by Softvision-RemusDranca** [comment]
I can't thoroughly verify this issue because I'm currently blocked by issues: #1959 and #2017. I'll verify this issue as soon as the mentioned ones are fixed.
