### ISSUE TITLE
Exiting immersive mode in Hubs leaves FxR frozen until Slow Script Dialog

### ISSUE THREAD

**Issue by larsbergstrom** [MozillaReality/FirefoxReality#1970]
## Configuration

Firefox Reality version: 1.4.1
Firefox Reality build ID: 

Hardware: HTC Vive Focus Plus

## Steps to Reproduce

1. Enter a Hubs room in VR
2. Exit VR, but stay at 2D

## Current Behavior

The entire UI is unresponsive. Home button, back, etc. do not work. Eventually  (>1 minute) the slow script dialog will come up and we can kill it.

## Expected Behavior

Browser still functions.

## Error Logs and Stack Traces

<details open>

```
```

</details>

**Comment by jvonitter** [comment]
@bluemarvin - possibly related to #1163 or #1625 ?

**Comment by bluemarvin** [comment]
I can only reproduce the issue on the Focus so probably not related. If I enable e10s, while hubs still freezes, I am still able to reload the page and FxR remains responsive. So something is hanging the content process.

**Comment by jvonitter** [comment]
@Softvision-GeluHaiduc @Softvision-RemusDranca Can you help us gather more data about this one?

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 6-32902155 (93816a5a) installed on the Oculus Go, Quest, HTC Vive Focus, Focus Plus and Lenovo Mirage Solo headsets.
Here are my findings:

**HTC Vive Focus Plus** - On the first try after entering the room I pressed the back button on the controller, the UI was frozen, after a few seconds the “Warning: Unresponsive script” popup appeared, the ok button was clicked, the UI started to respond again slowly. ([video](https://drive.google.com/file/d/1SB8sVy4no_OVetmRh6Ki-Mm1XpRmY9Ql/view?usp=sharing) and [logs](https://drive.google.com/file/d/1eGzShtLFExFWpjJEGyiBfMpI1glfSqa0/view?usp=sharing))
The app was forecekilled and I tried to enter the room again but instead it entered in theater mode.

**Oculus Quest** - On the first try when trying to enter the room it entered immersive mode quickly and then exited, I clicked the “Enter VR” button and again it quickly entered and exited immersive mode. At the third attempt the headset got stuck in entering immersive mode, quitting or resuming the app doesn't unblock the browser, after a forcekill the app can be used again. ([video](https://drive.google.com/file/d/1gDR-zzokQ_2TtbriNMNCJoOKeJDVFceP/view?usp=sharing) and [logs](https://drive.google.com/file/d/1cwqjwfucGPUu3vF5p3MZFW66jfVSQPS_/view?usp=sharing))
After the forcekill I tried to enter another room and this time it entered immersive mode, the headset was removed for a few seconds and put back, immersive mode was exited and the initial scenario was again reproducible.

**Oculus Go** - On the first try when trying to enter the room it entered immersive mode and then exited, the action hapende slower then on the quest, I clicked the “Enter VR” button and again the same thing happened. At the third attempt the headset got stuck in entering immersive mode, quitting or resuming the app doesn't unblock the browser, after a forcekill the app can be used again. ([video](https://drive.google.com/file/d/1l1tGA5wcbrogLSSgHxlnrTF7qUNyC9ue/view?usp=sharing) and [logs](https://drive.google.com/file/d/1weY6ug_wuXKfLszlbAzFycCLXqOjnwaS/view?usp=sharing))
After the forcekill I tried to enter another room and this time it entered immersive mode but the movements were really choppy.

**Lenovo Mirage Solo** - The same behaviour as on the oculus go could be observed here as well.
After the forcekill I tried to enter another room and this time it entered immersive mode but it froze at the first frame, the headset was removed for a few seconds and put back, immersive mode was exited and the initial scenario was again reproducible. ([logs](https://drive.google.com/file/d/1cd8_RtqV_mmZEEXiP03Yi0cR9vBqJaY5/view?usp=sharing))

**HTC Vive Focus** - Everything works as expected, I could exit immersive mode, reenter immersive mode, navigate, no crashes no glitches nothing froze. ([video](https://drive.google.com/file/d/12A-EkWkViutS4tlIhFcSY0GC6W07otUX/view?usp=sharing) and [logs](https://drive.google.com/file/d/13pBbHrqTg9VDBNe7ydauYvICl86Xz-sQ/view?usp=sharing))


If you need additional information or you want me to test a specific scenario please let me know.

**Comment by MortimerGoro** [comment]
@Softvision-GeluHaiduc can you review again when https://github.com/MozillaReality/FirefoxReality/pull/2018 lands? it includes a regression fix that at least should fix the mentioned Oculus device issues.

**Comment by MortimerGoro** [comment]
#2018 already landed

**Comment by Softvision-GeluHaiduc** [comment]
@MortimerGoro I have verified this issue with the latest Firefox Reality version 6-32911705 (bcecc731) installed on the Oculus Go and Oculus Quest headsets.
The issue is no longer reproducible on the Oculus headsets, although on the Oculus Go the movements are lagging a bit but entering and exiting immersive mode multiple times from hubs is possible.

**Comment by philip-lamb** [comment]
@gfodor FYI.

**Comment by bluemarvin** [comment]
This still reproduces on Focus with latest FxR.

**Comment by bluemarvin** [comment]
If this can't be fixed in v6 we will need to not show hubs in the feed for Focus devices.

**Comment by bluemarvin** [comment]
I upgraded to the latest GeckoView (72.0.20191023094816) and am still able to reproduce.

**Comment by bluemarvin** [comment]
hubs is hanging in the following script on exit:
`VRB[SessionStack]: Slow script: https://assets-prod.reticulum.io/hubs/assets/js/hub-c8df0ff1282216f098f6.js`

I tried using the remote debugger to get more information but was unable to.

**Comment by daoshengmu** [comment]
I got the same result as @bluemarvin 's (https://github.com/MozillaReality/FirefoxReality/issues/1970#issuecomment-545667128). I also tried to revert the change of [a regression](https://bugzilla.mozilla.org/show_bug.cgi?id=1588177) that happens to Sketchfab, but it still doesn't work for us.

**Comment by MortimerGoro** [comment]
I found the problem after some research (bypassing the Gecko HTTPS rules was really helpful to debug Hubs JavaScript locally)

It's a Hubs issue. Pushed  a PR there with the details: https://github.com/mozilla/hubs/pull/1873

**Comment by larsbergstrom** [comment]
Awesome investigation tracking this down, @MortimerGoro!
