### ISSUE TITLE
Changing the UA causes the page to be entered into history after each change.

### ISSUE THREAD

**Issue by bluemarvin** [MozillaReality/FirefoxReality#2894]
## Configuration

Firefox Reality version: v9

Hardware: All

## Steps to Reproduce

1. Change UA in hamburger menu.

## Current Behavior

Page is entered again into history.

## Expected Behavior

Page should not be added again to history.

## Notes
This is caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1618664
Regressed by: https://github.com/MozillaReality/FirefoxReality/pull/2893

**Comment by bluemarvin** [comment]
This is mostly fixed by #2949

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 10-140842123 (28cd6766) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
Unfortunately, the issue is still present. Using different webpages changing the User-Agent from the hamburger menu duplicates the feeds in the History View.

**Comment by bluemarvin** [comment]
I am not able to reproduce this. What website are you using? Please note that you will see many different permutations of the website in history if the page does redirects or location changes. For example `twitch.tv` does a lot of location changes so when changing the UA you will see up to four different URL in the history page. However, if you press the back button, it should got back to the previous page. This is what my history looks like after visiting `twitch.tv` and switching between desktop and VR UA multiple times:
![image](https://user-images.githubusercontent.com/3066/77554265-16bcfc80-6e73-11ea-922e-e18608dc8ece.png)
However if I press the back button I am taken to the webxr.today URL and not one of the twitch URL permutations.

**Comment by Softvision-GeluHaiduc** [comment]
Sorry for the misunderstanding, I interpreted the issue wrong, if you navigate back it shows the previously visited webpage. 
I have verified this behavior with the latest Firefox Reality version 10-140852325 (25447532) installed on the Oculus Go, HTC Vive Focus Plus, Pico Neo2 and Pico G2 headsets.
I will close the issue.
