### ISSUE TITLE
Muted videos with autoplay not being played

### ISSUE THREAD

**Issue by fernandojsg** [MozillaReality/FirefoxReality#3351]
## Configuration

Firefox Reality version: 10 (master)
Firefox Reality build ID: ea7a9e0

Hardware: Oculus Quest

## Steps to Reproduce

1. Visit a website that has a video with autoplay and `muted` attribute on it:
  - https://threejs.org/examples/?q=video#webxr_vr_video
  - http://pauljadam.com/demos/autoplay-loop-muted-controls.html

## Current Behavior

The video is not being played

## Expected Behavior

The video should start playiing as soon as the page has been loaded.

fwiw I tried it on Oculus Browser, Chrome Desktop and Firefox desktop and android and it worked correctly in all of them.

**Comment by keianhzo** [comment]
@fernandojsg We are accepting/rejecting based on the Autoplay setting in Settings -> Display. Did you have the Autoplay setting enabled there? For what I understand we should play only if autoplay is enabled. I guess OB has it enabled by default. Fenix does the same as us.

**Comment by fernandojsg** [comment]
@keianhzo but I believe that settings should be in order to revert the policy of stop autoplay of audios or videos with audio as https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio
But as described on the article ```Muted autoplay is still allowed. So script can set the “muted” attribute on HTMLMediaElement to true, and autoplay will work.``` and that's the behaviour I'm experiencing with all the other browsers without changing the default settings (ffox or fenix included). So I still feel that's should be working that way in FxR without need to change any default settings.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified this issue with the latest Firefox Reality version 10 RC6 (140fb700) installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets.
Unfortunately, the issue is still reproducible. Muted videos are not autoplayed unless the “Autoplay Media” setting is enabled.

**Comment by bluemarvin** [comment]
The was not landed in v10. The fix is only in master and will be part of v11.

**Comment by Softvision-GeluHaiduc** [comment]
I have verified the issue on the wrong build, I've retested it on the latest master, Firefox Reality version 11-141391233, installed on the Oculus Go, HTC Vive Focus Plus and Pico G2 4K headsets, and the issue is no longer reproducible. Muted videos are autoplayed.
