### ISSUE TITLE
Daydream can't click WebXR.today featured items

### ISSUE THREAD

**Issue by dustinkerstein** [MozillaReality/FirefoxReality#554]
## Hardware
Pixel XL and Moto Z

## Steps to Reproduce
1. Launch FirefoxReality with Daydream (1st generation is the only one I've tested)
2. Note the controller works on native buttons (ie. settings) but can't click featured gallery items (webxr.today)
3. Go to a different site (ie. Google) and note the controller works fine

<details open>

```
```

</details>

**Comment by cvan** [comment]
Thanks for filing! Fixed in production. Didn't catch this on my Oculus Go before QA'ing release.

**Comment by dustinkerstein** [comment]
Nice! Quick question - Will this require a new APK or should it just work with the current build now?

**Comment by cvan** [comment]
> Nice! Quick question - Will this require a new APK or should it just work with the current build now?

the Content Feed/Home page is hosted remotely, so it'll work with a refresh of the Home button. :+1: thanks again!

**Comment by dustinkerstein** [comment]
K, I just tried on Daydream (original version) after a re-launch and it's still the same behavior. Any debug I can get you?

**Comment by dustinkerstein** [comment]
Resetting the app cache did it. Thanks!
